from pathlib import Path

from appconf import AppConf
from django.conf import settings


class DjangoViteAppConf(AppConf):
    """
    This class contains all default settings. They all get applied to the "global"
    Django settings, with the specified prefix of "DJANGO_VITE_".
    """

    # If using in development or production mode.
    DEV_MODE = False
    # Default Vite server protocol (http or https)
    DEV_SERVER_PROTOCOL = "http"
    # Default vite server hostname.
    DEV_SERVER_HOST = "localhost"
    # Default Vite server port.
    DEV_SERVER_PORT = 3000
    # Default Vite server path to HMR script.
    WS_CLIENT_URL = "@vite/client"

    REACT_REFRESH_URL = "@react-refresh"

    # Location of Vite compiled assets (only used in Vite production mode).
    # Must be included in your "STATICFILES_DIRS".
    # In Django production mode this folder need to be collected as static
    # files using "python manage.py collectstatic".
    ASSETS_PATH = ""

    # Prefix for STATIC_URL
    STATIC_URL_PREFIX = ""

    # Path to your manifest file generated by Vite.
    # Should be in "DJANGO_VITE_ASSETS_PATH".
    MANIFEST_PATH = (
        Path(settings.DJANGO_VITE_ASSETS_PATH)
        if settings.DJANGO_VITE_DEV_MODE
        else Path(settings.STATIC_ROOT) / settings.DJANGO_VITE_STATIC_URL_PREFIX
    ) / "manifest.json"

    # Motif in the 'manifest.json' to find the polyfills generated by Vite.
    LEGACY_POLYFILLS_MOTIF = "legacy-polyfills"

    class Meta:
        prefix = "django_vite"
